### ISSUE TITLE
wish: more flexible regex support for matching comment bindings

### ISSUE THREAD

**Issue by markstos** [regolith-linux/remontoire#10]
For example, this might be nice to use with Vim / Neovim, but the config files use '"" for comments rather than "#", so a different regex would be needed to match comments.

**Comment by kgilmer** [comment]
Hmm, I'll take a look.  Thanks for the suggestion @markstos

**Comment by kgilmer** [comment]
Remontoire 1.4 will include a new command line option `-p` that allows you to specify a prefix string to the comment bindings.  For example, if a `vimrc` file contains the following lines:
```
" ## category // action // keybinding ## ignored user comment
" Enable syntax highlighting
syntax on
```

Then launching Remontoire like this will render the commented line:
```
src/remontoire -c ~/.vimrc -p \"\ 
```

**Comment by markstos** [comment]
Fixed. Improved docs pending in #11.
