### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by jubalh** [regolith-linux/remontoire#12]
Can you please tag a release so that one can package it for Linux distributions?

**Comment by kgilmer** [comment]
Certainly!

https://github.com/regolith-linux/remontoire/releases/tag/1.4.0

**Comment by jubalh** [comment]
Awesome, thanks!
And here is the PR for the openSUSE package: https://github.com/regolith-linux/remontoire/pull/14
And submission into official repos: https://build.opensuse.org/request/show/849604

**Comment by kgilmer** [comment]
Nice, wow I like how concise these package spec files are.  Quite a bit less work than the debian stuff I'm doing!

**Comment by jubalh** [comment]
> Nice, wow I like how concise these package spec files are. Quite a bit less work than the debian stuff I'm doing!

Indeed! I maintain one package in Debian too. It is a hassle ;)
OBS helps a ton too. Some people seem to use it in Debian too: https://www.collabora.com/news-and-blog/blog/2016/10/24/open-build-service-in-debian/

**Comment by kgilmer** [comment]
Nice, thanks for the tip about OBS.  I had played around with it a few years back but something got stuck and I was unable to figure out what was happening and gave up.  I may need to give it another shot.
