### ISSUE TITLE
Wish: filter by keyword

### ISSUE THREAD

**Issue by markstos** [regolith-linux/remontoire#13]
As i3 is a keyboard-focused UI, having good support navigating the this app with the keyboard would be a natural fit.

One option is to add a text box to the top of the UI and launch with the text box focused. As the user types there, the UI filters the results to a fuzzy-find match of what's searched for.

A more radical alternative is to re-implement this using Rofi, which is built for displaying and filtering a list of text.

If the shortcut syntax was carefully constructed, after selecting a keyboard shortcut the app could "type" the shortcut and have it be activated.

To support that, users would havew to be careful to not create Remontoire comments like " <Super> HJKL" which don't correspond to a single keybinding and instead would needs to create 4 distinct comments for a case like that.

**Comment by kgilmer** [comment]
Yeah, I've had these thoughts too at times.  As-is Remontoire is intended to rely on a "passive" interface.  Meaning it doesn't consume any keyboard events.  This is to allow users to invoke it without breaking their workflow in an existing app such as a terminal.  But, of course you can use the mouse to expand/collapse sections so it's not strictly passive.  Nonetheless sticking with the unix philosophy of a program doing one thing, at this time I'm not inclined to add this feature.  I think Rofi or other ways of accessing keybindings in a more interactive workflow are certainly valuable to some users and think that may be a better approach than adding this functionality to Remontoire.

**Comment by markstos** [comment]
Thanks, I'll close this.

The fundamental idea of Remontoire of parsing comments to create a keyboard shortcut viewer is a great idea. Building on that idea, it shouldn't be to hard to build a rofi-based solution based on the same comment pattern for a motivated developer.
