### ISSUE TITLE
Adding FontAwesome as a soft dependency

### ISSUE THREAD

**Issue by marcocadete** [regolith-linux/remontoire#16]
I had a problem with remontoire not displaying font awesome icons, which made the areas where the icons should have been really big, causing remontoire to extend/overflow my screen.  

I wasn't aware that FontAwesome was required to fix the issue, until Ken Gilmer informed me.

So having this as a dependency would probably help others not have to go searching for answers, even though the Regolith community is very responsive, friendly and helpful.

A screenshot of the problem:  

![Screenshot from 2021-01-17 12-35-58](https://user-images.githubusercontent.com/28997066/104852508-abf61980-58fb-11eb-8d51-8be45b6c0c9b.png)

**Comment by iamjameswalters** [comment]
I concur; Font Awesome was missing from my install, I had to go looking for this on my own.

**Comment by kgilmer** [comment]
This was fixed in 1.6
