### ISSUE TITLE
How do I customize my Remontoire shortcuts window?

### ISSUE THREAD

**Issue by joeynguyen** [regolith-linux/remontoire#2]
Hi, I'm a new user to Regolith.  Enjoying it so far.  Thanks for the great project!

Question, if I were to customize my i3 settings to change my shortcuts away from what Regolith has set as the default, how do I also update the shortcuts cheatsheet generated by Remontoire?  Right now, it looks like it's hard-coded inside this repo's `src/window.vala` file.

It would be great if we could update it using a config file instead, for example: `~/.config/regolith/remontoire/config`.

Please let me know if this is already possible somehow.

**Comment by kgilmer** [comment]
Hi @joeynguyen , yep you're right on all fronts.  The current version of Remontoire is a "get it out the door" release and as such is pretty basic.  The plan is that once the support work of the new release (and new users) dies down a bit to add a feature to Remontoire to allow it to directly read shortcuts from your active i3 config file using https://github.com/altdesktop/i3ipc-glib.  There will need to be some kind of parsable comment format by which Remontoire can extract a category and textual description for each keybinding.  These comments will be added to the default Regolith i3 config file and when users make keybinding changes Remontoire will automatically be updated.

In addition to this feature, I want Remontoire to save/restore the close/open state of each category.  

Have you worked with Vala before?

**Comment by joeynguyen** [comment]
Thanks for the quick response.  That's good to know about the upcoming plans.

No I haven't worked with or heard of Vala until I saw that file.

**Comment by kgilmer** [comment]
The new version is available in `unstable` for testing.  A new version of the i3 config file is also available.  Documentation is currently missing but in essence, a comment line in the i3 config file structured like this will be parsed and loaded into Remontoire:

```
## <category> ## <description> ## <keybinding ##
```
