### ISSUE TITLE
"Super" key doesn't show up as in website screenshots [Ubuntu 16.04]

### ISSUE THREAD

**Issue by nachovizzo** [regolith-linux/remontoire#6]
After upgrading to regolith 1.4 (awesome changes) I can't see the little windows icon as in the website

![image](https://user-images.githubusercontent.com/21349875/80325500-c9ce9c00-880b-11ea-8e6a-22c781329ce7.png)

Am I missing something?
This is how my i3config file looks:
![image](https://user-images.githubusercontent.com/21349875/80325532-f2ef2c80-880b-11ea-907e-15187e1f7db6.png)

PS: I can't copy the windows super key character

Thanks

**Comment by kgilmer** [comment]
Interesting, the "windows" icon comes from the fontawesome font.  I expect that you have that installed because it's an explicit dependency, but perhaps you have another font that is superseding fontawesome.  Can you verify?  Here's what I have:

```bash
$ apt list --installed | grep awesome

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

fonts-font-awesome/eoan,eoan,now 5.0.10+really4.7.0~dfsg-1 all [installed,automatic]
```

**Comment by nachovizzo** [comment]
```sh
apt list --installed | grep awesome

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

fonts-font-awesome/bionic,now 4.7.0~dfsg-3 all [installed]

```

**Comment by kgilmer** [comment]
I need to look into how to specify that the fontawesome font is used by remontoire.  In the meantime, here is a list of installed fonts on my machine.  Perhaps there is an obvious one that you have that's overriding fontawesome.
[fonts.txt](https://github.com/regolith-linux/remontoire/files/4543400/fonts.txt)

**Comment by nachovizzo** [comment]
These are my fonts, looks a bit "outdated", I'm using Ubuntu Bionic 18.04:
[fonts.txt](https://github.com/regolith-linux/remontoire/files/4546046/fonts.txt)

**Comment by kgilmer** [comment]
I believe I may have a fix for this.  Can you run remontoire with the attached stylesheet, like:
```
./src/remontoire -t <path to style.css> -s $(printenv I3SOCK)
```

The stylesheet is available here: https://github.com/regolith-linux/remontoire/blob/master/data/style.css

**Comment by nachovizzo** [comment]
@kgilmer Thanks a lot! I confirm this solve the issue in my case

![image](https://user-images.githubusercontent.com/21349875/96422906-ec5cd300-11f8-11eb-9033-e916bf05d355.png)

**Comment by markstos** [comment]
This issue can be closed, it is is "Done".

**Comment by kgilmer** [comment]
Thanks @markstos
