### ISSUE TITLE
Problem with multiple monitors, different display sizes, placement of Remontoire

### ISSUE THREAD

**Issue by royrwood** [regolith-linux/remontoire#8]
With multiple monitors, Remontoire shows up and moves unpredictably.  If the secondary monitor has focus, Remontoire initially shows up centered on the secondary display, but then jumps back to the primary display (and warps the pointer with it) once you interact with Remontoire.

As well, if Remontoire is set to align "east", odd things happen with placement if the primary display size is smaller than the secondary monitor.  Remontoire tries to align to the right edge, but spills over into the secondary display, particularly when the dropdowns are toggled and the window size increases in width.  This may be because my primary display native size is 1920x1080 and I'm only running it at 1200x900.  The secondary is 1920x1080, and I'd need a different secondary that is a different size to confirm (I'll try to get access to another monitor to confirm).

**Comment by mikemaxfield** [comment]
similar problem.  I glanced at the code, the positing logic is quite simple, but I'm not that familiar with GTK and my reproduction doesn't seem to track from a ~"least-surprise" reading of the logic ... 

My setup:

- one 4k landscape on left, primary
- one 4k rotated/portrait on right

I see two issues:

1. I'm not able to get remontoire to open on the portrait screen at all.  It only opens on the landscape/primary no matter where I launch it from.  The code seems to get the monitor from the `window` object state ... should be grabbing the active display at that time?

1. then I have the same layout issue as the OP.  My portrait rises "higher" than the landscape/primary, so the actual virtual geometry of the 'canvas' really includes a dead space in the upper-left;  the logic needs to factor in screen offsets in addition to overall geometry/size of the monitor, not just its size, for the call to `window.move()`

**Comment by kgilmer** [comment]
I believe the GTK API's used to retrieve the dimensions of the monitors is not accounting for portrait/landscape modes.  There may be other issues in which the reported dimensions are merged across screens.  I haven't had a chance to look into it recently, but you may be able to work around the issue in the short term by changing the orientation setting in Remontoire to West or North (depending on your setup).

**Comment by kgilmer** [comment]
This was fixed in 1.4
