### ISSUE TITLE
wish: support for multiple "-c" flags

### ISSUE THREAD

**Issue by markstos** [regolith-linux/remontoire#9]
This is useful for other apps that don't have all keybindings a single file.

**Comment by kgilmer** [comment]
Good idea, thanks @markstos !

**Comment by kgilmer** [comment]
I addressed this by adding a new read option to consume from `stdin`.  This allows for arbitrary handling of files data that can be passed to Remontoire.  Example:

```
cat file1 file2 file3 | remontoire -i
```

**Comment by markstos** [comment]
Fixed. Improved docs pending in #11.
